version: '3.4'

volumes:
  prometheus_data: {}
  grafana_data: {}
  elasticsearch_data: {}

services:

  grafana:
    image: grafana/grafana:5.4.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: password

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    depends_on:
      - prometheus_gateway
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus:/etc/prometheus

  prometheus_gateway:
    image: prom/pushgateway:v0.6.0
    container_name: prometheus_gateway
    restart: unless-stopped
    ports:
      - 9091:9091

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch