version: 2.1

commands: 
    setup:
      steps:
        - run:
            name: Install/Update Docker Compose
            command: |
                curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose
        - run: 
            name: Docker Login
            command: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run: 
            name: Setup env vars
            command: |
                echo "export BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV 
                echo "export HASH=$CIRCLE_SHA1" >> $BASH_ENV 
                echo "export BUILD_USER=$CIRCLE_USERNAME" >> $BASH_ENV
                if [[ $CIRCLE_BRANCH =~ ([^-]+)-([^-]+)-([0-9]{1,2}\.[0-9]{1,3}\.[0-9]{1,4}) ]]; then
                  echo "export BUILD_PRODUCT=${BASH_REMATCH[1]}"
                  echo "export BUILD_CONFIGURATION=${BASH_REMATCH[2]}"
                  echo "export BUILD_NUMBER=${BASH_REMATCH[3]}" >> $BASH_ENV
                else
                  echo "export BUILD_NUMBER=${CIRCLE_BUILD_NUM}" >> $BASH_ENV  
                fi
                cat ${BASH_ENV}
    build:
      steps:
        - run: 
            name: Build
            command: make docker-build
    test:
      steps:
        - run: 
            name: Test
            command: |
                mkdir ~/test-results
                make docker-test | tee ~/test-results/tests.log
    publish:
      steps:
        - run:
            name: Push
            command: make docker-push

jobs:
  build:
    machine:
        docker_layer_caching: true
    steps:
      - checkout
      - setup
      - build
      - test
      - store_test_results:
          path: ~/test-results
  publish:
    machine:
        docker_layer_caching: true
    steps:
      - checkout
      - setup
      - build
      - publish

workflows:
  version: 2.1
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: /(.*?)release-\d{1,2}\.\d{1,3}\.\d{1,4}$/