global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus_gateway'
    static_configs:
      - targets: [
      'games:80',
      'prometheus_gateway:9091'
      ]